### ISSUE TITLE
Also show level 30 as milestone

### ISSUE THREAD

**Issue by tegob** [thomasdondorf/poke-level-calc#1]
At level 30, wild Pokémon are the strongest you can encounter. Since it’s the level cap for wild Pokémon, and since level 30 is _much_ more easily obtainable, why not show how long it would take to reach level 30 as well as level 40?

Or maybe make the goal level (which is the hardcoded value 40 at the moment) dynamic, so the user can change it to any level they like?

**Comment by thomasdondorf** [comment]
It's done with the last release. :)
