### ISSUE TITLE
Format of date is unclear

### ISSUE THREAD

**Issue by Artorp** [thomasdondorf/poke-level-calc#2]
When I first visited the site I entered the date in the day/month/2016 format. Turns out the format is month/day/year.

I suggest changing the infotext from "?/?/2016" to "month/day/2016" or similar.

**Comment by thomasdondorf** [comment]
Changed it to mm/dd/2016. Do you think it's clear now?

**Comment by Artorp** [comment]
Yup, much clearer. Good job.
