### ISSUE TITLE
Show the predicted date of achievement

### ISSUE THREAD

**Issue by Amorymeltzer** [thomasdondorf/poke-level-calc#4]
Rough estimates are fine of course, but it might be nice (and simple) to add the number of days to the current date, and give the predicted date alongside the time, i.e. "You will reach level 30 on mm/dd/yyyy (x months or zz days)" or something to that effect.

**Comment by thomasdondorf** [comment]
Thanks for the idea, but I'm currently not planning on developing the calculator any further.
