### ISSUE TITLE
Error using date in 2020

### ISSUE THREAD

**Issue by ukbigdave** [thomasdondorf/poke-level-calc#8]
Trying to use a date in 2020 seems to not calculate.

**Comment by vsdaan** [comment]
#9 I fixed that in this pr

**Comment by rangertaybes** [comment]
Where can it be found now?

**Comment by vsdaan** [comment]
[Here](https://theking465.github.io/poke-level-calc/)

**Comment by Raldris** [comment]
Still an error :(
